#!/usr/bin/env bash
# Builds the ICT Setups indicator and strategy from ONE rules file (ict-core.pine), so the chart
# and the backtest can never disagree. Edit ict-core.pine (rules) or ict-strategy-block.pine
# (orders only), then run: bash tradingview/build-ict.sh
set -euo pipefail
cd "$(dirname "$0")"

VER="$(date +%Y-%m-%d)"
DECL_ARGS='overlay=true, behind_chart=false, max_boxes_count=500, max_lines_count=500, max_labels_count=500, max_bars_back=500'

{
  echo '//@version=6'
  echo "// ICT SETUPS (indicator) — GENERATED by build-ict.sh from ict-core.pine on ${VER}. Do not edit."
  echo "indicator(\"ICT Setups — Liquidity · MSS · iFVG\", shorttitle=\"ICT Setups\", ${DECL_ARGS})"
  echo 'bool IS_STRATEGY = false'
  cat ict-core.pine
} > ict-setups.pine

if [[ -f ict-strategy-block.pine ]]; then
  {
    echo '//@version=6'
    echo "// ICT SETUPS (strategy) — GENERATED by build-ict.sh from ict-core.pine + ict-strategy-block.pine on ${VER}. Do not edit."
    echo "strategy(\"ICT Setups — Strategy\", shorttitle=\"ICT Setups S\", ${DECL_ARGS}, initial_capital=10000, default_qty_type=strategy.fixed, default_qty_value=1, pyramiding=0, slippage=1, backtest_fill_limits_assumption=1, use_bar_magnifier=true, process_orders_on_close=false, calc_on_every_tick=true, commission_type=strategy.commission.cash_per_contract, commission_value=1.03, margin_long=0, margin_short=0)"
    echo 'bool IS_STRATEGY = true'
    cat ict-core.pine
    cat ict-strategy-block.pine
  } > ict-setups-strategy.pine
fi

if [[ -f ict-selftest-block.pine ]]; then
  {
    echo '//@version=6'
    echo "// ICT SETUPS SELF-TEST — GENERATED by build-ict.sh from ict-core.pine + ict-selftest-block.pine on ${VER}. Do not edit."
    echo "indicator(\"ICT Setups — Self-test\", shorttitle=\"ICT Self-test\", ${DECL_ARGS})"
    echo 'bool IS_STRATEGY = false'
    cat ict-core.pine
    cat ict-selftest-block.pine
  } > ict-selftest.pine
fi

wc -l ict-setups*.pine ict-selftest.pine
